### ISSUE TITLE
Custom binarystore.xml is not installed in correct directory and not read by Artifactory

### ISSUE THREAD

**Issue by woyteck1** [jfrog/JFrog-Cloud-Installers#101]
**Is this a request for help?**: no

---

**BUG REPORT**

**Which installer**: ansible collection 1.1.2

**Which product and version** (eg: ansible & collection version - 1.1.2): version 1.1.2

**Which operating system and version**(eg: ubuntu & version - 20.4): 18.4 kernel 4.15.0-140-generic

**What happened**: 
A custom binarystore.xml file (variable binary_store_file points to a file) is available and it's copied to $ARTIFACTORYHOME/var/etc/binarystore.xml
However Artifactory ignores that.
When I copied that file into $ARTIFACTORYHOME/var/etc/artifactory/binarystore.xml
Then it got picked up, however Artifactory did not create the directory structure in the correct path.

**What you expected to happen**:
I expect it this file to be placed in correct path, so when Artifactory is initialized, it creates the directory structure in the place I want it to. 

**How to reproduce it** (as minimally and precisely as possible):
Create a custom binarystore.xml file and provide it via the variable.
Then run the playbook

**Anything else we need to know**:
This forces me to use the default installation file-store which is not what I require.

**Comment by chukka** [comment]
@woyteck1  Now  with this  [platform collection](https://github.com/jfrog/JFrog-Cloud-Installers/tree/master/Ansible/ansible_collections/jfrog/platform) , you can change your binarystore.xml contents in https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/binarystore.xml.j2

**Comment by woyteck1** [comment]
This is a hardcoded template in the galaxy collection.
Can you please make the location (source) of the template a variable? 
That would make the life easy to be able to point to a file that is in my ansible dir structure and not to edit a collection, that can be overwritten... 
For me this is still a bug.

**Comment by chukka** [comment]
@woyteck1 ok, Does it makes sense to add content of binarystore.xml as a variable and you can pass your XML content in that variable  ?

Can you  opening an new (same) issue for jfrog.platform collection as version 1.1.2 is deprecated

**Comment by chukka** [comment]
@woyteck1 We added an option  to configure  binarystore.xml (using `artifactory_binarystore` variable) , Hope this helps

**Comment by woyteck1** [comment]
Works fine now! Thanks!
