### ISSUE TITLE
[ansible] Add variable for PostgreSQL repo URLs

### ISSUE THREAD

**Issue by Uquout7o** [jfrog/JFrog-Cloud-Installers#111]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which installer**: Ansible

**Which product and version** (eg: ansible & collection version - 1.1.2): Ansible & collection version 7.18.6

**Which operating system and version**(eg: ubuntu & version - 20.4): Ubuntu 20.04.2

**What happened**: Postgres role fails to install, throwing "connection refused" when apt_key and apt_repository try to add the repository at https://www.postgresql.org

**What you expected to happen**: have a variable for the key and repo URL

**How to reproduce it** (as minimally and precisely as possible): run the Postgres role in an air-gapped environment

**Anything else we need to know**: I suggest to add a variable for the PostgreSQL repo and repo key URLs. The default variables can contain the internet URL, which can be overridden in case of an air-gapped environment.

**Comment by Uquout7o** [comment]
> @Uquout7o Can you please share steps just to reproduce this issue (logs helps)

- Run the postgres role on a Linux server that is not connected to the internet.
- Ansible output: 

`TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [lsm101artifdb02.example.com]
ok: [lsm101artifdb01.example.com]

TASK [jfrog.platform.postgres : define OS-specific variables] ******************************************************************************************************************************
ok: [lsm101artifdb02.example.com]
ok: [lsm101artifdb01.example.com]

TASK [jfrog.platform.postgres : perform installation] **************************************************************************************************************************************
included: /home/username/.ansible/collections/ansible_collections/jfrog/platform/roles/postgres/tasks/Debian.yml for lsm101artifdb02.example.com, lsm101artifdb01.example.com

TASK [jfrog.platform.postgres : install acl, python3-psycopg2] *****************************************************************************************************************************
changed: [lsm101artifdb01.example.com]
changed: [lsm101artifdb02.example.com]

TASK [jfrog.platform.postgres : add postgres apt key] **************************************************************************************************************************************
fatal: [lsm101artifdb01.example.com]: FAILED! => {"changed": false, "msg": "Failed to download key at https://www.postgresql.org/media/keys/ACCC4CF8.asc: Request failed: <urlopen error [Errno 111] Connection refused>"}
fatal: [lsm101artifdb02.example.com]: FAILED! => {"changed": false, "msg": "Failed to download key at https://www.postgresql.org/media/keys/ACCC4CF8.asc: Request failed: <urlopen error [Errno 111] Connection refused>"}`

**Comment by andrescolodrero** [comment]
i second that change, i use internal repo for debian packages.

**Comment by chukka** [comment]
Fixed internally, will be rolling out in next collection release
