### ISSUE TITLE
7.18.6 runs both nginx roles when ssl enabled.

### ISSUE THREAD

**Issue by woyteck1** [jfrog/JFrog-Cloud-Installers#112]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUR REPORT

**Which installer**: 7.18.6

**Which product and version** (eg: ansible & collection version - 1.1.2): 7.18.6

**Which operating system and version**(eg: ubuntu & version - 20.4): ubuntu 18.04

**What happened**: 
Both artifactory_nginx and artifactory_nginx_ssl roles run, but it should be just one of them.

according to the defaults:
```
# Set this to true when SSL is enabled (to use artifactory_nginx_ssl role), default to false (implies artifactory uses artifactory_nginx role )
artifactory_nginx_ssl_enabled: false

# Set this to false when ngnix is disabled, defaults to true (implies artifactory uses artifactory_nginx role )
artifactory_nginx_enabled: true
```

**What you expected to happen**:

I expect only artifactory_nginx_ssl to run when 
artifactory_nginx_ssl_enabled: true

**How to reproduce it** (as minimally and precisely as possible):

Set:
artifactory_nginx_ssl_enabled: true

then run installation.

**Anything else we need to know**:
artifactory_nginx_enabled should be used to enable/disable nginx completely, even if artifactory_nginx_ssl_enabled is true.

artifactory_nginx_ssl_enabled should be used to default to standard nginx or ssl version if true.

**Comment by chukka** [comment]
@woyteck1 Thanks for reporting , will be fixed in next release

**Comment by weakcamel** [comment]
I can confirm that as of 7.19.8, this role is now idempotent in my scenario. Thanks!
