### ISSUE TITLE
[ansible/artifactory] installation fails due to undefined variable

### ISSUE THREAD

**Issue by weakcamel** [jfrog/JFrog-Cloud-Installers#118]
**Is this a request for help?**:

No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Which installer**:

Ansible 7.18.6

**Which product and version** (eg: ansible & collection version - 1.1.2):

Artifactory, 7.18.6

**Which operating system and version**(eg: ubuntu & version - 20.4):

Ubuntu 20.04

**What happened**:

```
TASK [jfrog.platform.artifactory : Create required directories] ******************************************************************************************************************************************
ok: [artifactory.example.com] => (item=/data/jfrog-filestore)
ok: [artifactory.example.com] => (item=/opt/jfrog/artifactory/var/data)
ok: [artifactory.example.com] => (item=/opt/jfrog/artifactory/var/etc)
ok: [artifactory.example.com] => (item=/opt/jfrog/artifactory/var/etc/security/)
ok: [artifactory.example.com] => (item=/opt/jfrog/artifactory/var/etc/artifactory/info/)

TASK [jfrog.platform.artifactory : Configure systemyaml] *************************************************************************************************************************************************
changed: [artifactory.example.com]

TASK [jfrog.platform.artifactory : Configure master key] *************************************************************************************************************************************************
ok: [artifactory.example.com]

TASK [jfrog.platform.artifactory : Configure join key] ***************************************************************************************************************************************************
changed: [artifactory.example.com]

TASK [jfrog.platform.artifactory : Configure installer info] *********************************************************************************************************************************************
fatal: [artifactory.example.com]: FAILED! => changed=false
  msg: 'AnsibleUndefinedVariable: ''platform_collection_version'' is undefined'
```

**What you expected to happen**:

Successful installation.

**How to reproduce it** (as minimally and precisely as possible):

```
- name: Install and configure Artifactory
  hosts: artifactory_test
  become: true
  tasks:
    - include_role:
        name: jfrog.platform.artifactory
```

**Anything else we need to know**:

Workaround is relatively simple - to define this value in inventory.

**Comment by weakcamel** [comment]
Duplicate of https://github.com/jfrog/JFrog-Cloud-Installers/issues/119

**Comment by chukka** [comment]
@weakcamel  can you try running the whole collection instead of a single artifactory role  , since `platform_collection_version`  value is already defined from groupvars/all/package_version.yaml

**Comment by weakcamel** [comment]
@chukka Could you explain how to "run a collection"?

My understanding is that a collection is a set of roles you can mix and match, it's not a runnable on its own:

* https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/examples/playbook-rt.yml uses a role
* The collection structure explained here https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html doesn't mention embedding group variables inside a collection - is there another document which does?

**Comment by chukka** [comment]
@weakcamel  I generally test collection's specific role using below commands . Hope it helps

- cd /tmp
- vi hosts.ini #create inventory
- ansible-galaxy collection install jfrog.platform -p .
- ansible-playbook -vv ansible_collections/jfrog/platform/artifactory.yml -i hosts.ini

**Comment by weakcamel** [comment]
@chukka That's not how you use collections. Collections are modules meant to be **installed** into an existing code structure which is typically according to a variant of [standard directory](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout) which defines:

- user roles
- playbooks
- inventory, including group and host variables for *all* the managed hosts, of any type (Artifactory being just 1 of many)
- requirements to install *external* roles
- external roles/collections which by default get installed to /etc/ansible or ~/.ansible

Your setup is good for testing (`group_vars/all/package_version.yaml` gets included in the inventory of your *test* project)  but not feasible for *using* 
means making a collection the Ansible "root" directory - copying over whole inventory, user roles, playbooks **into** the source code of collection.  Doing it this way reverses the Ansible directory structure upside down.

**Comment by weakcamel** [comment]
@chukka well, this more or less this setup. Except we're not using the built-in **playbook** - why would we? our environment is different, we need a different one to set up the host from scratch (OS configuration)

**Comment by misse** [comment]
I would second @weakcamel, a collection is a collection of stand-alone roles, any variables needed by any individual role should be present in either defaults or vars (preferably defaults to allow it being overridden by the playbook) so that one might incorporate the role in ones own playbook.

**Comment by chukka** [comment]
Let me take a second look at it and come back next week

**Comment by weakcamel** [comment]
> any variables needed by any individual role should be present in either defaults or vars

+1


> (preferably defaults to allow it being overridden by the playbook) for that role, so that one might incorporate the role in ones own playbook.

In this specific situation: 

https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/group_vars/all/package_version.yml

* products' versions - yes, those need to be overridable (and I *believe* they're already redefined in the respective roles)
* `platform_collection_version` is pretty much a constant, so it's private - could _potentially_ be in  in `vars` of each role.

Ideal IMO would be to be able to pull this value from [collection galaxy metadata](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta) but I don't see a reasonable way to do that (unless - perhaps - with a very simple Python plugin which would provide that).

**Comment by chukka** [comment]
@weakcamel  Makes sense , looking at [Ansible 2.x preference of variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) , yes, we can override them. Do you have a better idea not to duplicate these versions in `group_vars/all/package_version.yml` and product default roles variables  ?

**Comment by weakcamel** [comment]
@chukka I'm afraid not. Product default versions IMO belong to the product roles, for the `platform_collection_version` I don't see a feasible way to not duplicate it. 

Perhaps this could be automatically updated as part of the collection's release procedure?
