### ISSUE TITLE
Ansible role fails in --check mode

### ISSUE THREAD

**Issue by woyteck1** [jfrog/JFrog-Cloud-Installers#119]
**Is this a request for help?**:
Yeah.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG REPORT

**Which installer**: 7.18.6

**Which product and version** (eg: ansible & collection version - 1.1.2): 7.18.6

**Which operating system and version**(eg: ubuntu & version - 20.4): ubuntu 18.04

**What happened**:
Ran artifactory installation from the collection jforg.platform

TASK [jfrog.platform.artifactory : Wait for artifactory to be fully deployed] *****************************************************************************************
fatal: [artifactory.mydomain]: FAILED! =>
  msg: 'The conditional check ''result.status == 200'' failed. The error was: error while evaluating conditional (result.status == 200): ''dict object'' has no attribute ''status'''

**What you expected to happen**:
I expect it to go through.

**How to reproduce it** (as minimally and precisely as possible):
Run the collection installation in --check mode

**Anything else we need to know**:
This is required for our CI to pass the --check mode.

**Comment by chukka** [comment]
@woyteck1  Can you please provide extract reproducible steps ? I would like to try , Also, Does this only happen with artifactory role , did you get a chance to verify on other roles too ?

**Comment by woyteck1** [comment]
OK, so I run our artifactory playbook in normal mode - then it installs and passes. However we also run the same playbook (connecting to the same host) with --check mode.
In checkmode, it doesn't really restart or start the artifactory, it merely pretends to do it. 

See below:
```

TASK [jfrog.platform.artifactory : Ensure permissions are correct] ****************************************************************************************************
ok: [artichoke.core.speechmatics.io]

RUNNING HANDLER [jfrog.platform.artifactory : restart artifactory] ****************************************************************************************************
changed: [artichoke.core.speechmatics.io]

TASK [jfrog.platform.artifactory : Wait for artifactory to be fully deployed] *****************************************************************************************
fatal: [artichoke.core.speechmatics.io]: FAILED! =>
  msg: 'The conditional check ''result.status == 200'' failed. The error was: error while evaluating conditional (result.status == 200): ''dict object'' has no attribute ''status'''
```

Therefore steps to reproduce it is to run the artifactory playbook (the one you know that passes) with --check option.

**Comment by chukka** [comment]
@woyteck1  Thanks, let me try this

**Comment by chukka** [comment]
Fix will be available in next release

**Comment by chukka** [comment]
@woyteck1  please try new [collection](https://galaxy.ansible.com/jfrog/platform) and share feedback :)
