### ISSUE TITLE
[Mission Control][Elasticsearch] . searchguard plugin anonymous_auth_enabled configuration

### ISSUE THREAD

**Issue by sergiocruzado** [jfrog/JFrog-Cloud-Installers#132]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Which installer**: Ansible

**Which product and version** (eg: ansible & collection version - 1.1.2): Mission Control

**Which operating system and version**(eg: ubuntu & version - 20.4): all

**What happened**: searchGuard plugin is not configured to allow anonymous HTTP request. the file /usr/share/elasticsearch/plugins/search-guard-7/sgconfig/sg_config.yml has the default config:
sg_config:
  dynamic:
    http:
        anonymous_auth_enabled: false

**What you expected to happen**: when run playbook the plugin searchGuard is configured to allow anonymous request. the file /usr/share/elasticsearch/plugins/search-guard-7/sgconfig/sg_config.yml must have this configuration:
sg_config:
  dynamic:
    http:
        anonymous_auth_enabled: true

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**: in case mission control deployment is using [helm chart](https://github.com/jfrog/charts/blob/219d3f7498f9da5258ac072280776c1e3243041b/stable/mission-control/templates/mission-control-statefulset.yaml#L265) a script "initializeSearchGuard.sh" is run.

**Comment by chukka** [comment]
will be fixed along with next release , 7.23.3
