### ISSUE TITLE
License? Contribution?

### ISSUE THREAD

**Issue by jared-schmidt-civ** [jfrog/JFrog-Cloud-Installers#142]
FEATURE REQUEST: open source license and instructions for contributing

This code base is posted, but there is no open source license associated with it.  I'd like to expand on what's here by adding to the code, but would like some contribution instructions and an open source license to know how to proceed.  If the instructions are that no external contributions outside of jfrog are accepted, that would be nice to know as well.

**Comment by vinayagg** [comment]
Hello Jared,
This repo should be Apache 2.0 License. I will look into fixing this.
In the mean time, we welcome contributions.
Feel free to create a fork, make your changes and create pull requests. When you create one, you will be prompted to sign an agreement. At that point we will review the PR.

If you have any additional questions, feel free to ask me.
