### ISSUE TITLE
artifactory requires net-tools, which is missing on ubuntu 20.04. Please install it.

### ISSUE THREAD

**Issue by rockdreamer** [jfrog/JFrog-Cloud-Installers#146]
**Which installer**: Ansible

**Which product and version**: ansible 2.11.2 jfrog-platform collection 7.21.12

**Which operating system and version** : ubuntu - 20.04

**What happened**: I tried to install on a clean Ubuntu VM using the artifactory role. Artifactory would fail to start.

**What you expected to happen**: Artifactory to start

**How to reproduce it** (as minimally and precisely as possible): try molecule and tests?

**Anything else we need to know**: After hours of troubleshooting, I pinpointed the issue: Ubuntu 20.04 doesn't ship with net-tools by default. I reverted the VM, installed net-tools and it all worked.

**Comment by chukka** [comment]
@rockdreamer Thanks for reporting this , will fix it in next release
