### ISSUE TITLE
[ansible/postgres] Default values are defined in vars/ instead of defaults/

### ISSUE THREAD

**Issue by Uquout7o** [jfrog/JFrog-Cloud-Installers#150]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**: Ansible

**Which product and version** (eg: ansible & collection version - 1.1.2): Ansible version ansible 2.9.24, collection version 7.23.3

**Which operating system and version**(eg: ubuntu & version - 20.4): Ubuntu 20.04.2

**What happened**:
Values are always pulled from roles/postgres/vars/Debian.yml first because of Ansible's variable precedence.
That's expected behavior of Ansible, but it prevents me from setting the vaules myself in my group_vars.

**What you expected to happen**:
Values for the following variables being pulled from my group_vars file:
postgresql_data_dir: 
postgresql_bin_path:
postgresql_config_path
postgresql_daemon
postgresql_external_pid_file
postgres_apt_key_url
postgres_apt_key_id
postgres_apt_repository_repo

**How to reproduce it** (as minimally and precisely as possible):
Use postgres role and define variables in group_vars

**Anything else we need to know**:
Suggestion: put the default values in roles/postgres/defaults/main.yml instead, like in the other roles.

**Comment by chukka** [comment]
@Uquout7o Thanks for sharing this, will fix this in next release

**Comment by chukka** [comment]
@Uquout7o Can you try on the latest collection version and share feedback ?
