### ISSUE TITLE
Unable to install artifactory with ssl enabled

### ISSUE THREAD

**Issue by lookshe** [jfrog/JFrog-Cloud-Installers#151]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
artifactory_nginx_ssl

**Which product and version** (eg: ansible & collection version - 1.1.2):
ansible collection latest version

**Which operating system and version**(eg: ubuntu & version - 20.4):
Ubuntu 20.04

**What happened**:
```
TASK [install nginx with SSL] *******************************************************************************************************************************************************************************

TASK [jfrog.platform.artifactory_nginx_ssl : Configure the artifactory nginx conf] **************************************************************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "checksum": "2782e7940a7e9e1255537bb79a10d1a4d2a276ae", "msg": "Destination directory /etc/nginx/conf.d does not exist"}
```

**What you expected to happen**:
nginx to be installed

**How to reproduce it** (as minimally and precisely as possible):
Try to install artifactory with artifactory_nginx_enabled set to false and artifactory_nginx_ssl_enabled set to true on a fresh system installation.

**Anything else we need to know**:
The role artifactory_nginx_ssl does not install and configure nginx the same way artifactory_nginx does it. It is impossible to run the role without previously running artifactory_nginx or install nginx separately.

**Comment by chukka** [comment]
Thanks for the PR , we would like to review and test internally
