### ISSUE TITLE
Create Upgrade.yaml version that supports using docker-compose

### ISSUE THREAD

**Issue by rg026287** [jfrog/JFrog-Cloud-Installers#156]
**Is this a request for help?**:

No, we have received help via email, this is an enhancement request.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

This is a feature request. Currently the wiki page for how to upgrade Mission Control (https://www.jfrog.com/confluence/display/JFROG/Upgrading+Mission+Control#UpgradingMissionControl-UpgradingfromVersion4.xto4.x) supports upgrade using  Docker Compose, RPM and Debian. As with many orgs, we are set up to use Docker Compose. The Ansible Playbook does not user docker-compose for its processes, and will require manually modifying steps in the playbook files when we go to run it to keep in format with our installation method. This request is asking to have options available based on how you want to upgrade; for example, an upgrade-debian.yaml, upgrade-rpm.yaml and upgrade-docker-compose.yaml options to choose from, or parameters we can pass to choose which option from the upgrade.yaml role is used.

**Which installer**:
Mission Control (though Distribution and XRay would also be great)

**Which product and version** (eg: ansible & collection version - 1.1.2):
Ansible 2.9, Mission Control 4.7.11

**Which operating system and version**(eg: ubuntu & version - 20.4):
RHEL 7.8

**What happened**:
We need to upgrade and wish to automate the process, published playbook does not use docker-compose method

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
We have received manual steps from JFrog Enterprise Solution Lead, we are not holding up our upgrade because of this, would simply like this to be available for future upgrades/installations for Mission Control and other JFrog Products.

**Comment by chukka** [comment]
@rg026287 Our ansible collections are based on linux archive (platform independent) and Not sure about supporting other flavours like docker compose in near future
