### ISSUE TITLE
Pre configure custom base url field is missing

### ISSUE THREAD

**Issue by proseti** [jfrog/JFrog-Cloud-Installers#168]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
Latest

**Which operating system and version**(eg: ubuntu & version - 20.4):
Centos 7.9

**What happened**:
Cant pre configure custom base url field. When I install two nodes in HA architecture , then 'custom base url' field is filled by hostname one of the nodes.

**What you expected to happen**:
Want to be able to pre configure custom base url field.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
It would be really helpful in HA configurations.

**Comment by chukka** [comment]
This is already fixed in  `7.25.7` release , first `hostname` will be taken as custom base url', hope this helps

**Comment by proseti** [comment]
@chukka you mean first VM hostname where its triggered, yes? But what If I have all these VMs (in HA configuration) behind Load Balancer and I want to set custom base url to LB DNS Name?

**Comment by chukka** [comment]
@proseti  you can override this [value](https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/group_vars/all/vars.yml#L7) `jfrog_url`
