### ISSUE TITLE
Error with "Deploy to Azure" button 

### ISSUE THREAD

**Issue by denisbuco** [jfrog/JFrog-Cloud-Installers#182]
When I click on the "Deploy to Azure" Button I´m forwarded to my Azure Portal an this error message is showing up: "There was an error downloading the template from URI 'https://raw.githubusercontent.com/jfrog/JFrog-Cloud-Installers/arm-xray/AzureResourceManager/Artifactory/azuredeploy_ms_ps.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

Any idea how to fix this?

**Comment by danielmkn** [comment]
@denisbuco, thanks for reporting the issue! It's fixed now
