### ISSUE TITLE
Sticky Session for ELB & Health Check not using doc's recommendations

### ISSUE THREAD

**Issue by diginc** [jfrog/JFrog-Cloud-Installers#19]
My team is spinning up a Terraform HA stack and when testing an upload to Artifactory we noticed it was bouncing between our 2 different artifactory ids between the upload/depoly requests.  The JFrog documentation on [how to setup an HA cluster ](https://jfrog.com/knowledge-base/how-to-setup-artifactory-ha-cluster-in-aws/) specifically mentions needing sticky sessions.  A quick search of the repo for 'sticky' didn't show any hits so this may apply to CFN/Azure too?

Another small difference is for the [LB health check the documentation](https://jfrog.com/knowledge-base/what-is-the-best-practice-to-configure-a-health-check-for-artifactory-in-amazon-elb/) recommends hitting the `/artifactory/api/system/ping` URI instead of `/webapp/#/login` which is currently configured in terraform.

**Comment by jfrog-aparicio** [comment]
> JFrog documentation on how to setup an HA cluster specifically mentions needing sticky sessions. A quick search of the repo for 'sticky' didn't show any hits so this may apply to CFN/Azure too?

The requirement for sticky session has been removed, so you should not need it.

> Another small difference is for the LB health check the documentation recommends hitting the /artifactory/api/system/ping URI instead of /webapp/#/login which is currently configured in terraform.

That can be changed to the system ping but that has two issues:
1. It requires a valid license for api/system/ping to return a good check, meaning you can't add the license via the UI in a first time set up
2. The api/system/ping may require credentials depending on the securty configurations, though this credential check can be disabled via an Artifactory property

**Comment by jfrog-aparicio** [comment]
> JFrog documentation on how to setup an HA cluster specifically mentions needing sticky sessions. A quick search of the repo for 'sticky' didn't show any hits so this may apply to CFN/Azure too?

The requirement for sticky session has been removed, so you should not need it.

> Another small difference is for the LB health check the documentation recommends hitting the /artifactory/api/system/ping URI instead of /webapp/#/login which is currently configured in terraform.

That can be changed to the system ping but that has two issues:
1. It requires a valid license for api/system/ping to return a good check, meaning you can't add the license via the UI in a first time set up
2. The api/system/ping may require credentials depending on the securty configurations, though this credential check can be disabled via an Artifactory property

**Comment by diginc** [comment]
What we were seeing is testing uploads fails the first try because we're bouncing between servers according to the browser request headers `Artifactory-ID: <hash>`

The AMI/stack is using artifactory version 6.9 and we were trying to spin it up w/6.9 first and then test how the upgrade process work.  Was the requirement for sticky sessions removed after version 6.9?

**Comment by diginc** [comment]
We tried upgrading to 6.13.1 and still had the problem uploading a file through the UI without sticky sessions.  Turning sticky sessions on addressed the problem.

**Comment by ShreyasNBS** [comment]
@diginc Can you please tell me how you enabled sticky sessions? The link in the article you referreed to is broken. Is there some NGINX Artifactory config you had to do to enable sticky sessions? The only other artifactory.conf I found was HA was [here](https://github.com/jfrog/artifactory-docker-examples/blob/master/files/nginx/conf.d/ha/artifactory.conf)

**Comment by butch12** [comment]
@ShreyasNBS I've experience the same thing as @diginc using this terraform template.  We added the following to our main.tf to enable sticky sessions on the AWS elb (note we had to switch the load balancer port 443 protocol from tcp to https in order to use sticky sessions):

```
resource "aws_app_cookie_stickiness_policy" "arti-http-cookie" {
  name          = "artifactory-elb-stickiness-http-cookie"
  load_balancer = aws_elb.web.name
  lb_port       = 80
  cookie_name   = var.session_cookie
}

resource "aws_app_cookie_stickiness_policy" "arti-https-cookie" {
  name          = "artifactory-elb-stickiness-https-cookie"
  load_balancer = aws_elb.web.name
  lb_port       = 443
  cookie_name   = var.session_cookie
}
```

**Comment by ShreyasNBS** [comment]
@butch12 Thank you. I will try this out.

**Comment by jfrog-aparicio** [comment]
Closing as this integration is deprecated.
