### ISSUE TITLE
[Ansible/nginx-ssl] Allow using external TLS certificates

### ISSUE THREAD

**Issue by weakcamel** [jfrog/JFrog-Cloud-Installers#195]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Which installer**:

Ansible / nginx-ssl

**Which product and version** (eg: ansible & collection version - 7.24.2):
n/a

**Which operating system and version**(eg: ubuntu & version - 20.4):
Generally (in my case Ubuntu 18.04)

**What happened**:

Current role for Nginx requires passing in variables containing:
* the TLS certificate **value** for the instance
* the certificate key **value**

This is fine if you have a self-signed (or externally signed) certificate purchased specifically for your Artifactory instance, but it doesn't work with e.g. LetsEncrypt or ZeroSSL certificates which are being renewed every 3 months asynchronously  (see e.g. https://certbot.eff.org/)

**What you expected to happen**:

It would be very beneficial for LetsEncrypt and similar PKI deployments to let people decide - and pass in just the certificate (and key) **paths** (and have those managed externally with e.g. certbot).

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by chukka** [comment]
@weakcamel  Are you referring that we support  TLS certificate  path rather than values so that even if certificate changes , install flow doesn't break ?

**Comment by weakcamel** [comment]
@chukka Yes, pretty much.

Currently the role assumes it has full control over a TLS certificate, but that may not be true if certificate is being managed by e.g. [_certbot_](https://certbot.eff.org/) or https://github.com/zerossl/zerossl-bot (Letsencrypt, Zerossl).

In that case certificate is being refreshed automatically on the host upon expiration date (typically 3 months) and that means running current Artifactory role would normally overwrite the certificate with an expired one.

**Comment by rahulsadanandan** [comment]
@weakcamel we have added an internal tracking ticket for this.

**Comment by bbaassssiiee** [comment]
Would overriding these templates help?

```yaml
artifactory_conf_template: templates/custom/artifactory.conf.j2
nginx_conf_template: templates/custom/nginx.conf.j2
```

**Comment by chukka** [comment]
Closed via https://github.com/jfrog/JFrog-Cloud-Installers/pull/292
