### ISSUE TITLE
Access/Secrect Key

### ISSUE THREAD

**Issue by JackyShu** [jfrog/JFrog-Cloud-Installers#2]
Does file '/var/opt/jfrog/artifactory/etc/binarystore.xml' is only for S3 access, if so, probably use role instead of key for security reason.

**Comment by jainishshah17** [comment]
[Here](https://www.jfrog.com/confluence/display/RTF/Configuring+the+Filestore#ConfiguringtheFilestore-S3BinaryProvider) is a way to use role instead of Keys to access S3.
