### ISSUE TITLE
[Ansible] Make usable for Amazonlinux2 Distribution

### ISSUE THREAD

**Issue by MatrixCrawler** [jfrog/JFrog-Cloud-Installers#206]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which installer**: Ansible Collection

**Which product and version** (eg: ansible & collection version - 7.24.2): 10.3.2

**Which operating system and version**(eg: ubuntu & version - 20.4): Amazonlinux2

**What happened**: I could not install on an Amazonlinux 2 System

**What you expected to happen**: I would like to use the collection on an Amazonlinux2 System

**How to reproduce it** (as minimally and precisely as possible): Set up an Amazonlinux2 Server and try to install the collection with ansible

**Comment by rahulsadanandan** [comment]
@MatrixCrawler We have created a ticket internally to track this. We are planning to add this our roadmap.
