### ISSUE TITLE
Installer on RHEL does tarball install instead of rpm install

### ISSUE THREAD

**Issue by cdalessio0131** [jfrog/JFrog-Cloud-Installers#221]
Is this a request for help?:

No.

Is this a BUG REPORT or FEATURE REQUEST? (choose one):

FEATURE REQUEST

On RHEL8, the playbook installs the pgdg and nginx-stable repos then installs postgresql-13 and nginx from those repos.  This is a awesome.  However, it then goes and does an Artifactory tarball install.  Why doesn't it install the Artifactory repo then install Artifactory from that repo just like it does for the others?

Which installer:
Artifactory, but it could apply to others.

Which product and version (eg: ansible & collection version - 1.1.2):
Ansible 2.12.6
Artifactory 7.38.10
JFrog Platform 10.6.2

Which operating system and version(eg: ubuntu & version - 20.4):
RHEL 8.6

What happened:
Playbook installed Artifactory from tar file.

What you expected to happen:
Playbook to install Artifactory rpm

How to reproduce it (as minimally and precisely as possible):
N/A

**Comment by rahulsadanandan** [comment]
Hi @cdalessio0131 
we use tar file installation to support multiple flavours not specific  to RPM based installation

**Comment by cdalessio0131** [comment]
I figured that was the reason. But since you needed to be RedHat specific for postgresql and nginx, why not go all the way for a RedHat install?

**Comment by cdalessio0131** [comment]
As admin, I prefer to have the yum/dnf logging as well as rpm verify for my installed package.

**Comment by rahulsadanandan** [comment]
For PostgreSQL and Nginx third-party libraries we went with upstream vendor packages.
For Jfrog products, we wanted to have uniform installation method across different flavors.

**Comment by cdalessio0131** [comment]
Disappointed, but I understand the reason behind the decision.  Thank you.
