### ISSUE TITLE
Changing postgres_data_dir caused postgres service startup to fail

### ISSUE THREAD

**Issue by cdalessio0131** [jfrog/JFrog-Cloud-Installers#223]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**:

Postgres

**Which product and version** (eg: ansible & collection version - 7.24.2):

ansible 2.12.6
jfrog.platform 10.6.2

**Which operating system and version**(eg: ubuntu & version - 20.4):

RHEL 8.6

**What happened**:

I changed _postgres_data_dir_ to _/data/postgres/data_.
The platform created the database in the new location and set **PGDATA** to the correct location in _/etc/profile.d/postgres.sh_.
However, the postgresql-13 service failed to start because the following line in _/usr/lib/systemd/system/postgresql-13.service_ was left unchanged.
```
Environment=PGDATA=/var/lib/pgsql/13/data/
```
Error:
```
ExecStartPre=/usr/pgsql-13/bin/postgresql-13-check-db-dir ${PGDATA} (code=exited, status=1/FAILURE)
```
```
/usr/pgsql-13/bin/postgresql-13-check-db-dir /var/lib/pgsql/13/data
"/var/lib/pgsql/13/data" is missing or empty.
Use "/usr/pgsql-13/bin/postgresql-13-setup initdb" to initialize the database cluster.
```

**What you expected to happen**:

The database should come up pointing at the correct location for **PGDATA**.

**How to reproduce it** (as minimally and precisely as possible):

Change the value of _postgres_data_dir_ to anything other than default.

**Anything else we need to know**:

Removing the _Environment=_ line from _/usr/lib/systemd/system/postgresql-13.service_ does not fix it.  Apparently, is must be changed.

**Comment by cdalessio0131** [comment]
Another option is to remove the _ExecStartPre_ line and modify the _ExecStart_ line to remove the _-D $PGDATA_ option.

**Comment by cdalessio0131** [comment]
Yet another option could be to use _systemctl set-environment PGDATA=????_.  This would override the PGDATA setting in the service file.  No need to change the service file.

**Comment by chukka** [comment]
@cdalessio0131 Thanks for reporting ! Sorry missed this , let us check and come back

**Comment by bbaassssiiee** [comment]
Systemd has its own way, shell scripts won't help you. Systemd is configured with unit files. The one for PostgreSQL comes with the package. If you need to override the PGDATA environment variable with a custom value like in your `postgresql_data_dir`, then the role needs to "Drop-In" a systemd override and run systemctl daemon-reload.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/10671559/228526498-ada0b621-9d0a-4156-a01d-30df6bdcb10b.png">

**Comment by bbaassssiiee** [comment]
The bug is fixed in a PR open since March 29th.

https://github.com/jfrog/JFrog-Cloud-Installers/pull/279

**Comment by chukka** [comment]
Closed via https://github.com/jfrog/JFrog-Cloud-Installers/pull/292
