### ISSUE TITLE
[Ansible] Unable to install Artifactory on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by sondreengebraten** [jfrog/JFrog-Cloud-Installers#234]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Which installer**: Ansible 

**Which product and version** (eg: ansible & collection version - 7.24.2):

ansible 2.9.6

collections [10.8.3] - Aug 18, 2022

**Which operating system and version**(eg: ubuntu & version - 20.4):

Ubuntu 20.04

**What happened**:

Install fails on "when" conditionals. 

**What you expected to happen**:

Install should succeed

**How to reproduce it** (as minimally and precisely as possible):

Following the steps from https://www.jfrog.com/confluence/display/JFROG/Installing+the+JFrog+Platform+Using+Ansible#InstallingtheJFrogPlatformUsingAnsible-SettingupAnsibleandtheJFrogAnsibleCollection

Fails with: 

`TASK [artifactory : Configure system.yaml] ***********************************************************************************************************
fatal: [artifactory.***.com]: FAILED! => {"msg": "The conditional check 'artifactory_systemyaml is defined' failed. The error was: error while evaluating conditional (artifactory_systemyaml is defined): 'dict object' has no attribute 'postgres_servers'\n\nThe error appears to be in '/home/user/.ansible/collections/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml': line 110, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configure system.yaml\n  ^ here\n"}`

**Anything else we need to know**:

**Comment by chukka** [comment]
@sondreengebraten looks like issue with your inventory file `postgres_servers` is not defined , please check

**Comment by sondreengebraten** [comment]
You are correct. Adding the following to the inventory resolves this issue: 

`    postgres_servers:
      hosts:
        artifactory.domain.com:
          ansible_host: 10.10.10.10
    artifactory_servers:
      hosts:
        artifactory.domain.com:
          ansible_host: 10.10.10.10
    xray_servers:
      hosts:
        artifactory.domain.com:
          ansible_host: 10.10.10.10
    distribution_servers:
      hosts:
        artifactory.domain.com:
          ansible_host: 10.10.10.10
    insight_servers:
      hosts:
        artifactory.domain.com:
          ansible_host: 10.10.10.10`

Now I instead get this error: 

`fatal: [artifactory.domain.com]: FAILED! => {"msg": "The conditional check 'user_ownerships.stdout_lines | length > 0' failed. The error was: error while evaluating conditional (user_ownerships.stdout_lines | length > 0): 'dict object' has no attribute 'stdout_lines'"}
`

**Comment by sondreengebraten** [comment]
I am trying to setup a simple artifactory server for a small dev team. I am wondering if Docker would be a better option. Suggestions?

**Comment by chukka** [comment]
@sondreengebraten IMHO, try out [artifactory helm chart](https://github.com/jfrog/charts/tree/master/stable/artifactory) on Kubernetes  !  If that is not an option , Ansible is the second best one (where you can configure artifactory with external postgresql [recommended], should work OOB)

you just need to provision 2 servers and create a inventory as below

```
# Replace x.x.x.x  with public Ips of servers
[postgres_servers]
postgres-1 ansible_host=x.x.x.x

[artifactory_servers]
artifactory-1 ansible_host=x.x.x.x
```

**Comment by sondreengebraten** [comment]
Thanks for the suggestion. Helm is not an option, so I think ansible is the way to go. Postgre install fails on task create user with error: 

```
fatal: [artifactory.domain.com]: FAILED! => {"msg": "Unable to look up a name or access an attribute in template string ({{ database | dict2items | map(attribute='value') | list }}).\nMake sure your variable name does not contain invalid characters like '-': dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
```

**Comment by chukka** [comment]
Looks like you are trying to run postgres role on artifactory server . Also, are you trying to install postgresql and artifactory on same server ? can you run ansible -vvv (verbose) and share logs

**Comment by sondreengebraten** [comment]
I was trying to install both on the same server yes. After talking to support they suggested two servers. This makes no difference. Same error. 

```
The conditional check 'curr_user.enabled | bool' failed. The error was: error while evaluating conditional (curr_user.enabled | bool): 'curr_user' is undefined

The error appears to be in '/home/user/.ansible/collections/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml': line 67, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Create user
  ^ here
fatal: [artifactorypostgre.utgard.sh]: FAILED! => {
    "msg": "Unable to look up a name or access an attribute in template string ({{ database | dict2items | map(attribute='value') | list }}).\nMake sure your variable name does not contain invalid characters like '-': dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."
```

**Comment by chukka** [comment]
@sondreengebraten  is this still an issue ? can you share your inventory file and commands used to run ansible playbook ?

**Comment by itssiri** [comment]
Closing this ticket. Feel free to reopen in case issue persists.
