### ISSUE TITLE
[Ansible/artifactory] artifactory license update doesn't work for single node

### ISSUE THREAD

**Issue by weakcamel** [jfrog/JFrog-Cloud-Installers#246]
**Is this a request for help?**:

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):

* Ansible collection 10.8.2 (yet same issue with current colletion after checking the code)
* Artifactory 7.46.6
* Ansible 6.5.0

**Which operating system and version**(eg: ubuntu & version - 20.4):

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

**What happened**:

Updating license key (upgrade from Pro to Enterprise) via Ansible doesn't have any effect when you're not using HA mode.

**What you expected to happen**:

According to https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml#L12 the only variable these days for provisioning the license is `artifactory_licenses` which puts the license key into `var/etc/artifactory/artifactory.cluster.license` on filesystem.

That doesn't have any effect on a single node Artifactory, no matter if you restart it or not.
Only after changing `var/etc/artifactory/artifactory.lic` was the license actually applied and no restart was needed.

This used to be configurable by `artifactory_single_license` variable but that has been deprecated

**How to reproduce it** (as minimally and precisely as possible):

* install license on Artifactory single node
* update `artifactory_licenses` with a different license key and run Ansible again
* verify that the license in Artifactory UI hasn't changed

**Anything else we need to know**:

n/a

**Comment by chukka** [comment]
@weakcamel  I think its by design , https://www.jfrog.com/confluence/display/JFROG/Helm+Charts+for+Advanced+Users#HelmChartsforAdvancedUsers-AddingLicenses . Same applies for Ansible 

```
This method is relevant for initial deployment only. Once Artifactory is deployed, you should not keep passing these parameters, since the license is already persisted into Artifactory's storage (and they will be ignored). Updating the license should be done via Artifactory UI or REST API.
```

**Comment by weakcamel** [comment]
@chukka That's documentation for Helm deployments which is significantly different.

Otherwise:
https://jfrog.com/knowledge-base/artifactory-how-to-replace-the-license-key-for-your-artifactory-instance/

> Manually install the license key in the filesystem

>   * Go to the $ARTIFACTORY_HOME/etc/ folder.
>   * Edit/create the artifactory.lic file, replacing the key already inside the file with your new one. (Path is relevant for Artifactory up to version 6.x. From version 7.x the path of the artifactory.lic is $ARTIFACTORY_HOME/var/etc/artifactory)
>   * To allow the new key to load, restart Artifactory.

The last bit is actually not true

I've experimented a bit and once you update the license in UI, `artifactory.lic` changes on filesystem too. And vice versa: once I updated `artifactory.lic` manually on filesystem, Artifactory noticed the change (there were log messages about refreshing the license) and picked it up as well.

Ansible by its very nature should be [dempotent](https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#desired-state-and-idempotency) - you should be able to re-run it 20 times a day and if there are no changes needed, it should just be a no-op.

Having a different license configured in Artifactory itself and in the Ansible code base which provisioned would break this rule - you would break your instance running Ansible again.

**Comment by chukka** [comment]
@weakcamel Thanks for detailed description .I'm aware of ansible's idempotency. Here, we switched  from `artifactory.lic` license to `artifactory.cluster.license` to support both single /HA Nodes. For backward compatibility purposes,we will support placing both of the files: If both files exist, artifactory will load artifactory.lic (upgrade scenario)

 So workaround this issue , Manually update license via UI for one time and you can have same license placed in `artifactory_licenses` defaults.yaml file 

hope this helps

**Comment by weakcamel** [comment]
@chukka thanks!

> Here, we switched from artifactory.lic license to artifactory.cluster.license to support both single /HA Nodes. 

This is the key. I don't believe `artifactory.cluster.license` works for single node at all, that's what my tests have shown me.
