### ISSUE TITLE
[Ansible/artifactory] installService.sh script will never be launched during an upgrade

### ISSUE THREAD

**Issue by anael-l** [jfrog/JFrog-Cloud-Installers#251]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Which installer**: Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2): ansible collection version: 10.9.3

**Which operating system and version**(eg: ubuntu & version - 20.4): RHEL 8

**Which product license** (Enterprise/Pro): Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**: After the upgrade all NPM request with the "%2f" char (example: /artifactory/api/npm/npm/@angular-extensions%2fpretty-html-log) ended in the Apache 404 page

**What you expected to happen**: functionnal NPM requests

**How to reproduce it** (as minimally and precisely as possible): upgrade Artifactory using the collection

**Anything else we need to know**:
With a bit of research, we found that we faced this issue: https://jfrog.com/knowledge-base/artifactory-why-does-my-linux-archive-service-installation-fail-degrade-after-an-upgrade/
The solution is the run the "installService.sh" script that will recreate the "setenv.sh" script in the tomcat bin directory.

The version 10.9.0 of the collection should have fixed this issue as explained by the changelog: 
"Added installService.sh for upgrading Artifactory [GH-238](https://github.com/jfrog/JFrog-Cloud-Installers/pull/238)"

However there is an issue in the file: Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/install_service.yml

```yaml

- name: Create artifactory service
  become: yes
  command: "{{ artifactory_home }}/app/bin/installService.sh"
  args:
    creates: "{{ artifactory_service_file }}"

```

The **creates** param is described in the Ansible doc as: 
A filename or (since 2.0) glob pattern. If a matching file already exists, this step **will not be run**.
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#parameter-creates

As this is an upgrade, the artifactory service file already exists. Meaning that during an upgrade, the installService.sh script will never be launched, and won't recreate the "setenv.sh" script in the tomcat bin directory. That is why we had to do it manually.

To fix this, you either need to remove the "creates" line, or replace it.

**Comment by chukka** [comment]
@anael-l Thanks for raising this , this will be fixed with along with 10.11.x of platform release.
