### ISSUE TITLE
Issue with terraform on 3/19/23 

### ISSUE THREAD

**Issue by skasimalla** [jfrog/JFrog-Cloud-Installers#272]
Terraform issue: 

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid quoted type constraints
│
│   on variables.tf line 116, in variable "aws_amis":
│  116:   type = "map"
│
│ Terraform 0.11 and earlier required type constraints to be given in quotes, but that form is now deprecated and will
│ be removed in a future version of Terraform. Remove the quotes around "map" and write map(string) instead to
│ explicitly indicate that the map elements are strings.

**Comment by danielmkn** [comment]
Hi @skasimalla. The Terraform configuration in this repository is [deprecated](https://github.com/jfrog/JFrog-Cloud-Installers/commit/01fa5b0f9656bfc1d5e77871e18e8730ab8ef683) 3 years ago.
