### ISSUE TITLE
[artifactory/ansible] TLSv1.1 is deprecated.

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#273]
https://github.com/jfrog/JFrog-Cloud-Installers/blob/75b3c0cb03d6379d61ab45d4f3c25ce45519bcc4/Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/artifactory.conf.j2#L12

Reference: [Strong crypto defaults in RHEL 8 and deprecation of weak crypto algorithms](https://access.redhat.com/articles/3642912)

**Comment by bbaassssiiee** [comment]
Documentation needs an update as well:
https://jfrog.com/help/r/jfrog-artifactory-documentation/configuring-nginx

**Comment by chukka** [comment]
Closed via https://github.com/jfrog/JFrog-Cloud-Installers/pull/292
