### ISSUE TITLE
Template doesn't comply with our security policies

### ISSUE THREAD

**Issue by skasimalla** [jfrog/JFrog-Cloud-Installers#274]
If we run this terraform - it's triggering a bunch of security alerts by security bot

**Comment by danielmkn** [comment]
Hi @skasimalla. The Terraform configuration in this repository is [deprecated](https://github.com/jfrog/JFrog-Cloud-Installers/commit/01fa5b0f9656bfc1d5e77871e18e8730ab8ef683) 3 years ago.
