### ISSUE TITLE
[ansible/artifactory] wrong permissions on systemd unit file

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#283]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
Ansible collection jfrog-platform-10.12.1

**Which product and version** (eg: ansible & collection version - 7.24.2):
```
ansible [core 2.13.3]
  config file = /home/alma/.ansible.cfg
  configured module search path = ['/home/alma/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alma/py3/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/alma/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/alma/py3/bin/ansible
  python version = 3.9.13 (main, Nov 16 2022, 10:51:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

**Which operating system and version**(eg: ubuntu & version - 20.4):
Almalinux 8.7

**Which product license** (Enterprise/Pro):
All

**JFrog support reference** (if already raised with support team): 

**What happened**:
```text
Configuration file /usr/lib/systemd/system/artifactory.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Configuration file /usr/lib/systemd/system/artifactory.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
```

**What you expected to happen**:
No errors, nor warnings, Artifactory starts and runs stable.

**How to reproduce it** (as minimally and precisely as possible):
`tail -f /var/log/messages` after `systemctl start artifactory`

**Anything else we need to know**:
QA

**Comment by kammathavaran** [comment]
We will check and come back here.

**Comment by bbaassssiiee** [comment]
This should be fixed in the source of the product.

**Comment by bbaassssiiee** [comment]
Not an installer bug.

**Comment by chukka** [comment]
This is fixed internally , will be part of next minor release of artifactory , 7.98.x
