### ISSUE TITLE
Potential problems on Openshift 4.4+

### ISSUE THREAD

**Issue by megabreit** [jfrog/JFrog-Cloud-Installers#29]
Openshift 4.4+ is dealing differently with modified or mutated SCCs.
At every update the default SCCs are restored to their default, meaning that all additions (users) are removed and all modifications are undone.
See https://bugzilla.redhat.com/show_bug.cgi?id=1818893 for details.
Since you require to add a service account to anyuid SCC and patch the restricted SCC, your installation will break after the first Openshift update.
Recommendation is to create own SCCs and use RBAC to access the SCC.
A much better way of course would be to create images that are able to deal with dynamic, unprivileged uids... and not rely on SCCs :-)

**Comment by peters95** [comment]
@megabreit Thanks for bringing this up to our attention in the future release of openshift. Quick question are you referencing the helm based installation into openshift or the operator? I believe our anyuid SCC patch is only necessary for helm. We already use RBAC in our operator. I will look into it to see if we can bring the same solution to our helm please confirm this is what you are asking for. Thanks!

**Comment by megabreit** [comment]
@peters95 I didn't deploy anything yet. I just read the documentation and stumbled upon the SCC thingy.

**Comment by peters95** [comment]
@megabreit I will update the documentation thanks to be more precise. To deploy our opeartors via the OperatorHub no SCC changes need to be made. If you desire to use helm which has more configuration options you will need to add the SCC patch for now shown below:

`oc patch scc restricted --patch '{"fsGroup":{"type":"RunAsAny"},"runAsUser":{"type":"RunAsAny"},"seLinuxContext":{"type":"RunAsAny"}}' --type=merge`

This will patch the built-in restricted scc and I believe it should work in 4.4+ but needs to be tested against 4.4+. Current GCP Infra Openshift installer only supports 4.3.x clusters. Let me know if there is anything else I can help with.

**Comment by peters95** [comment]
Decision was made to remove support for helm based installations. Going to remove helm as an option for JFrog products into Openshift to avoid any upgrade path issues w/ our customers. Instead only our Operators will be supported that do not require this SCC patch. Thank you @megabreit for bringing this to our attention.
