### ISSUE TITLE
[ansible/artifactory] Postgresql.org is a busy site, package downloads could benefit from a gentle retry handler.

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#293]
https://github.com/jfrog/JFrog-Cloud-Installers/blob/9d46194903af2cb8303d502a7b199336353ebf66/Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/RedHat.yml#L45

Installation can fail due to transient network issues reported like:
```
urlopen error _ssl.c:880: The handshake operation timed out
```

**Comment by chukka** [comment]
@bbaassssiiee  Thanks for raising this , can you please raise a PR for the same

**Comment by bbaassssiiee** [comment]
> @bbaassssiiee Thanks for raising this , can you please raise a PR for the same

It's up for review...
