### ISSUE TITLE
[ansible/artifactory] artifactory role fails when run twice due to stopping artifactory service

### ISSUE THREAD

**Issue by PolaricEntropy** [jfrog/JFrog-Cloud-Installers#307]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
- ansible [core 2.14.6]
- community.general 7.1.0  
- jfrog.platform 10.13.2

**Which operating system and version**(eg: ubuntu & version - 20.4):
Ubuntu 20.04

**Which product license** (Enterprise/Pro):
N/A

**JFrog support reference** (if already raised with support team): 

**What happened**:
The artifactory service does not start if running a playbook a second time with the artifactory role, causing the "Make sure artifactory is up and running" task to fail. This makes the artifactory role non-idempotent.

This is due to the "Install Service" task running the second time the playbook runs (even though the service is already installed). Thus, the artifactory service is stopped if it is already running and there is no handler setup to start/restart the artifactory service in this scenario.

**What you expected to happen**:
I expect the artifactory role to be idempotent, so running a playbook with it a second time, if artifactory is already installed, to do no changes and the final task of the role to execute successfully.

**How to reproduce it** (as minimally and precisely as possible):
Run a playbook with the artifactory role twice. The first run will succeed, and the second run will fail on the "Make sure artifactory is up and running" task because the artifactory service has now stopped and has not been restarted. Worth noting is that the "Restart artifactory" tasks runs to flush all handlers, but this does nothing and does not start the service.

**Anything else we need to know**:
Optimal resolution: If the service is already installed, do not run the "Install Service" task to install the service since this will stop the service if its already running.

**Comment by chukka** [comment]
@PolaricEntropy Thanks for the issue , Let me investigate  this , Mean while is it possible for you a raise a PR with tentative fix , Happy to review it
