### ISSUE TITLE
[ansible/artifactory] Allow customizing binarystore.xml

### ISSUE THREAD

**Issue by gbx-andrew-schneider** [jfrog/JFrog-Cloud-Installers#313]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
both?

Prior to jfrog.platform 10.13.3, binarystore.xml could be customized by overriding artifactory_binarystore
10.13.3 removed that variable and doesn't appear to have introduced an alternate method to customize binarystore.xml
We're using S3 to store our binaries, and it is now impossible to accommodate that

**Which installer**:
ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
jfrog.platform 10.13.3+

**Comment by chukka** [comment]
@gbx-andrew-schneider  yes, currently default binarystore is moved to [templates](https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/binarystore.xml.j2) 

Looks like `artifactory_binarystore` variable is needed to customize anyway , I will provide a patch as soon as possible

**Comment by chukka** [comment]
@gbx-andrew-schneider Thanks for raising this , Fix is available in platform collection `10.14.1` using same `artifactory_binarystore` variable , please try and share feedback

**Comment by gbx-andrew-schneider** [comment]
Hey @chukka, looks like this is working as expected again. Thanks for the quick turnaround!
