### ISSUE TITLE
[ansible/Artifactory] bundles a PostgreSQL driver, downloading from Maven.org in an issue

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#315]
https://github.com/jfrog/JFrog-Cloud-Installers/blob/e0f14ca449060f192fecbd7d8400e76978942189/Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml#L171

The tarball includes a driver. When installing in an airgapped site whitelisting 'maven.org' is like opening Pandora's box (for shops not using Java).

**Comment by chukka** [comment]
@bbaassssiiee is there any possible workaround  you can suggest ?

**Comment by chukka** [comment]
@bbaassssiiee FYI , artifactory binary internally bundles  PostgreSQL driver by default , you can disable this task if its a air gapped environment

**Comment by bbaassssiiee** [comment]
It should be the other way around because the download is currently conditional on a value defined in the defaults. I.e. this is always true now:

```yaml
  when:
    - postgres_driver_download_url is defined
```

**Comment by bbaassssiiee** [comment]
A block with a Boolean `download_postgres_driver` would do.

**Comment by chukka** [comment]
yes , makes sense , I'll try to provide a solution in upcoming patch

**Comment by chukka** [comment]
@bbaassssiiee  you can set `postgres_driver_download` to `false` for airgap environments

**Comment by bbaassssiiee** [comment]
Thanks!!
