### ISSUE TITLE
[ansible/platform] No tags in github repo for releases.

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#333]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
All

**Which operating system and version**(eg: ubuntu & version - 20.4):
All

**Which product license** (Enterprise/Pro):
All

**JFrog support reference** (if already raised with support team): 

**What happened**:
No usable tags in Github repo for testing

**What you expected to happen**:
I'd like to test updates, but have now way to refer to a release because it is not tagged in Git.

**How to reproduce it** (as minimally and precisely as possible):

git checkout 10.13.1

**Anything else we need to know**:
To find the `artifactory_version` installed, we'll need to track the [jfrog/platform/roles/artifactory/defaults/main.yml
](https://github.com/jfrog/JFrog-Cloud-Installers/commits/master/Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml)

**Comment by bbaassssiiee** [comment]
We can use a requirements.yml file to install a release. But no easy way to browser the corresponding code on Github.

**Comment by srinivasgowda097** [comment]
@bbaassssiiee  Thanks for raising the enhancement , we would internally check and take up as enhancement.

**Comment by bbaassssiiee** [comment]
This is how to do it: [https://git-scm.com/book/en/v2/Git-Basics-Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)

What are you waiting for? Management escalation?

**Comment by bbaassssiiee** [comment]
Closing stale issue.

**Comment by chukka** [comment]
@bbaassssiiee we introduced the  tags with #435  release , please [check](https://github.com/jfrog/JFrog-Cloud-Installers/releases/tag/ansible%2Fplatform%2F10.20.4)
