### ISSUE TITLE
Hotfix for issue #294 in latest release

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#341]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
HOTFIX in PR

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):

**Which operating system and version**(eg: ubuntu & version - 20.4):

**Which product license** (Enterprise/Pro):
Enterprise/Pro/All

**JFrog support reference** (if already raised with support team): 
271636

**What happened**:
Template was not applied, install failed.

See issue #294 

**What you expected to happen**:
Template applied

**How to reproduce it** (as minimally and precisely as possible):
Install latest release with Ansible

**Anything else we need to know**:
Filename needed a fix.

**Comment by chukka** [comment]
Fixed via #343
