### ISSUE TITLE
Local install of artifcatory using ansible?

### ISSUE THREAD

**Issue by darthVikes** [jfrog/JFrog-Cloud-Installers#344]
Can I use this to install artifactory product only locally with ansible?  If so, what would need to be changed to only do the install for artifactory and any dependencies needed for artifactory? aka MySQL / nginx?

**Comment by chukka** [comment]
@darthVikes  can you provide more information on this ? locally means local machine ?

**Comment by darthVikes** [comment]
Yes, to a local machine VM running RHEL 8.x or 9.x  

Not a cloud ☁️instance.

**Comment by chukka** [comment]
You run as shown below [example](https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/examples/playbook-rt.yml) , it requires postgresql as dependency 

`ansible-playbook -vv examples/playbook-rt.yml -i hosts.ini
`

**Comment by bbaassssiiee** [comment]
You would need to `pip install ansible-core` and `ansible-galaxy collection install -r requirements.yml`:

```yaml
collections:
  - name: ansible.posix
  - name: community.postgresql
  - name: community.general
  - name: jfrog.platform
```

Your hosts file can be a simple as this:

```ini
[local:vars]
ansible_connection=local
server_name=artifactory.lan.local

[local:children]
artifactory_servers
postgres_servers

[artifactory_servers]
localhost ansible_host=127.0.0.1

[postgres_servers]
localhost ansible_host=127.0.0.1
```

**Comment by chukka** [comment]
Hope this helps, marking as closed
