### ISSUE TITLE
Avoiding IPv6 with extra JAVA_OPTION

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#347]
Some distributions have two entries for localhost in `/etc/hosts`:

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

This can cause Java apps trying binding using IPv6, which fails when that's disabled. This causes some tcp ports not listening, like the Artifactory router service. 

Solution: add an extra JAVA_OPTION: `-Djava.net.preferIPv4Stack=true`.

https://github.com/jfrog/JFrog-Cloud-Installers/blob/9158ae37089aead470009be6ede69e8118faf916/Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml#L39

```
artifactory_extra_java_opts: '-server -Xms512m -Xmx4g -Xss256k -XX:+UseG1GC -Djava.net.preferIPv4Stack=true'
```

**Comment by Logeshwarsn** [comment]
@bbaassssiiee Thanks for raising this issue. Did you had a chance to test this change from your end ? if it is tested then please provide us the artifactory-service.log with enabling this artifactory_extra_java_opts: '-server -Xms512m -Xmx4g -Xss256k -XX:+UseG1GC -Djava.net.preferIPv4Stack=true'

**Comment by Logeshwarsn** [comment]
@bbaassssiiee we would like to include in this readme instead of default in vars.

**Comment by Logeshwarsn** [comment]
@bbaassssiiee we would like to include in this readme instead of default in vars.

**Comment by bbaassssiiee** [comment]
[artifactory-service.log](https://github.com/jfrog/JFrog-Cloud-Installers/files/13510537/artifactory-service.log)
