### ISSUE TITLE
[ansible/artifactory] Upgrade version when tar is already present

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#357]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
ansible-core 2.16.2
collection version 10.16.3

**Which operating system and version**(eg: ubuntu & version - 20.4):
RHEL

**Which product license** (Enterprise/Pro):
Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:
When we run a deploy & update sometimes we have the download, and then the upgrade skips the relevant tasks.

**What you expected to happen**:
Upgrade

**How to reproduce it** (as minimally and precisely as possible):
Change artifactory_version, run playbook.

**Anything else we need to know**:
Better to grep the version from the property file in the app dir.

**Comment by chukka** [comment]
closed via #360
