### ISSUE TITLE
[ansible/postgres] failed to find PGDATA setting in -D.service

### ISSUE THREAD

**Issue by miki-sinmandella** [jfrog/JFrog-Cloud-Installers#36]
hi,
I am trying to deploy artifactory with ansible.
when I deployed Postgres I receive the error "failed to find PGDATA setting in -D.service".

**Comment by jefferyfry** [comment]
Are you running SELinux?

**Comment by wdrury-uk** [comment]
Im also getting this error on virtualbox lab - RHEL 7.8 VMs.

Also see related issue #58  I manually fixed by adding the missing variable to the postgres role/vars/Rehat.yml

```
TASK [jfrog.installers.postgres : initialize PostgreSQL database cluster] ****************************************************
task path: /root/.ansible/collections/ansible_collections/jfrog/installers/roles/postgres/tasks/main.yml:33
fatal: [postgres]: FAILED! => changed=true
  cmd:
  - /usr/pgsql-9.6/bin/postgresql96-setup
  - initdb
  - -D
  - /var/lib/pgsql/9.6/data
  delta: '0:00:00.035386'
  end: '2020-11-09 21:44:45.547958'
  msg: non-zero return code
  rc: 1
  start: '2020-11-09 21:44:45.512572'
  stderr: 'systemctl: invalid option -- ''D'''
  stderr_lines: <omitted>
  stdout: failed to find PGDATA setting in -D.service
  stdout_lines: <omitted>
```

**Comment by peters95** [comment]
@wdrury-uk Creating an internal bug ticket for the ansible team to dig into. Will notify you of any update.

**Comment by chukka** [comment]
Thanks @wdrury-uk for reporting , we currently support ubuntu only, we are planning to support RHEL, Centos 7.x /8.x in upcoming weeks (mostly next month)

**Comment by chukka** [comment]
@wdrury-uk  Workaround till we release official fix : 

After the error initialise the DB manually with below command and run the playbook again

`# /usr/pgsql-9.6/bin/postgresql96-setup initdb postgresql-9.6 -D /var/lib/pgsql/9.6/data`

**Comment by wdrury-uk** [comment]
Thanks for the fix @chukka will try this morning.

@peters95 just to confirm you mention this collection only supports unbuntu yet the postgres role is code to support only Debian and RedHat (RHEL)?  Did you mean those two OS?

Also can the ReadMe for the collection on Galaxy be extended to have section at top for Supported OS/Postgres Versions?

**Comment by wdrury-uk** [comment]
@chukka I can confirm the above fix, workaround being executed on the postgres db servers after first play execution failure with this issue error does solve the issue.

**Fix Steps**

1. Execute the play until errors
2. Logon each postgres db node and execute `[$] /usr/pgsql-9.6/bin/postgresql96-setup initdb postgresql-9.6 -D /var/lib/pgsql/9.6/data`
4. Re-execute play and postgres install completes with Success

**Comment by chukka** [comment]
Great ! lets wait for the fix in the upcoming release :)
