### ISSUE TITLE
[ansible/Artifactory] PostgreSQL 11 EOL

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#364]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Which installer**:
Ansible 

**Which product and version** (eg: ansible & collection version - 7.24.2):
latest

**Which operating system and version**(eg: ubuntu & version - 20.4):
RHEL8

**Which product license** (Enterprise/Pro):
Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:
```
Status code: 404 for https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-8-x86_64/repodata/repomd.xml (IP: 217.196.149.55)
Error: Failed to download metadata for repo 'pgdg11': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**What you expected to happen**:

The postgres role should disable the postgres repos it does does not use.

**How to reproduce it** (as minimally and precisely as possible):
Run the playbook on an existing install.

**Anything else we need to know**:
Screenshots in https://github.com/jfrog/JFrog-Cloud-Installers/issues/361

**Comment by bbaassssiiee** [comment]
Workaround:

```sh
#  yum config-manager --disable pgdg11
```

**Comment by Logeshwarsn** [comment]
Hi @bbaassssiiee Is this issue resolved ? or you want us to check this ?
