### ISSUE TITLE
[ansible/artifactory] Missing usage of migrate.sh

### ISSUE THREAD

**Issue by muellerju-thn** [jfrog/JFrog-Cloud-Installers#379]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT  
(I'm not really shure if this is a bug report or feature request though)

We currently have Artifactory installed via the rpm repo. To identify possible problems that could arise from migrating over to the ansible role, I compared the rpm (including pre- and post-install scripts) to the ansible role.

Beside smaller differences, I noticed that during postinstall, the rpm calls a (rather long) migration script at `app/bin/migrate.sh`, but I did not find a task in the role that does that.  

Is this a bug or anticipated?

**Which installer**: ansible/artifactory (jfrog.platform.artifactory)

**Comment by chukka** [comment]
@muellerju-thn `app/bin/migrate.sh` was used for  artifactory's  6.x to 7.x migration , not related to RPM specific .
