### ISSUE TITLE
[ansible/artifactory] Support for customizing arifactory.system.properties file

### ISSUE THREAD

**Issue by sparshs413** [jfrog/JFrog-Cloud-Installers#401]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
Artifactory

**Which operating system and version**(eg: ubuntu & version - 20.4):
Rocky 9

**Which product license** (Enterprise/Pro):
Enterprise+

**JFrog support reference** (if already raised with support team): 

**What happened**:
In the current setup we do not have a template for arifactory.system.properties file similar to system.yaml or binarystore file. It makes difficult to customize the same file and we have to set these properties manually.

**What you expected to happen**:
There should be a template added for cusotmizing the arifactory.system.properties file to enable features like enabling metrics for federated repositories, and updating the time to check for plugins updates etc. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gitta-jfrog** [comment]
Hi @sparshs413 

For Artifactory System Properties, we have an alternative to arifactory.system.properties.
You can pass the properties by using JavaOps in the system.yaml. see example:

```
shared:
  extraJavaOpts: "-Dartifactory.access.client.max.connections=50"
  ```
  
This method is according to our best practices and similar implementation can be found in our Helm Chart. 

Thanks
Yarden
