### ISSUE TITLE
No development effort on JFrog-Cloud-Installers

### ISSUE THREAD

**Issue by bbaassssiiee** [jfrog/JFrog-Cloud-Installers#402]
PUBLIC NOTICE

**Which installer**:
Ansible

**Which product and version** (eg: ansible & collection version - 7.24.2):
ansible & collection version - all

**Which operating system and version**(eg: ubuntu & version - 20.4):
all

**Which product license** (Enterprise/Pro):
Enterprise/Pro

**JFrog support reference** (if already raised with support team): 

**What happened**:

Technical debt accumulating.

**What you expected to happen**:

With such license fees we expect you would be able to pay a skilled person to actually maintain this installer of your enterprise product. Apparently JFrog lost people with Ansible knowledge, and didn't hire someone with enough skills to work on this repository.

**How to reproduce it** (as minimally and precisely as possible):

Just wait and see that pull-requests take forever to be merged. The only changes merged are version updates of the product downloaded

**Anything else we need to know**:
Sonatype Nexus is a competitive product with an active Ansible community around it.

**Comment by vasukinjfrog** [comment]
Hi @bbaassssiiee,

Thanks for bringing this, feedback noted and regret any inconvenience that may have been caused. Rest assured, we are working on the PRs provided and would take some time to see them being merged or change requests back to originator, based on our internal process alignments. I will be closing this with this comment as a feedback and do watch this space for updates.
