### ISSUE TITLE
[ansible/xray] RHEL 9 missing depedency install: libdb-utils (equivalent of DB5-Utils)

### ISSUE THREAD

**Issue by EmptyByte** [jfrog/JFrog-Cloud-Installers#422]
`Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/expect.yml`

On RHEL expect scenario will fail with:
```
spawn ./install.sh -u xray -g xray

[1mBeginning JFrog Xray setup[0m

[38;5;197m[ERROR[0m[38;5;197m] [0mSome dependencies [ Db-Utils-5.3 ] the product needs are missing
[38;5;197m[ERROR[0m[38;5;197m] [0mPlease check Prerequisites section under https://service.jfrog.org/installer/Installing+Xray#InstallingXray-LinuxArchiveInstallation on instructions to install them and then try again
```

The workaround is to install the libdb-utils package manually:
```
dnf install libdb-utils
```

- A task or vars with prerequisite packages is required to install it.
- The link in the scenario is dead.

Once installed the expect scenario succeeds.

**Comment by chukka** [comment]
@EmptyByte Could you please share which version of RHEL was used?

**Comment by EmptyByte** [comment]
Hi @chukka, it was RHEL9. Not sure if this happens on RHEL8 too.
