### ISSUE TITLE
Terraform template_file limit hit when using several licenses

### ISSUE THREAD

**Issue by jfrog-aparicio** [jfrog/JFrog-Cloud-Installers#5]
The terraform template_file has a limit of 16k characters. The default userdata.sh file is itself 6.5k characters and a single E+ license can be about 4k characters. In addition, SSL certs and other variables also push the character count up. This causes the terraform apply action to fail:

`expected length of user_data to be in the range (0 - 16384), got #!/bin/bash ....`

**Comment by jainishshah17** [comment]
@jfrog-aparicio I think we can make License filed nonmandatory as we are using different endpoint for the health check. That will now allow the user to install license after Artifactory cluster is deployed.

**Comment by maheshjfrog** [comment]
Updated Terraform/variables.tf. Now, License inputs are not mandatory.

**Comment by maheshjfrog** [comment]
Confirmed with Arturo for closure on this request.
