### ISSUE TITLE
[ansible/nginx] Unable to restart service nginx: Job for nginx.service failed because...

### ISSUE THREAD

**Issue by wdrury-uk** [jfrog/JFrog-Cloud-Installers#60]
New issue, this time the last tasks to restart nginx is failing due to SELinux permission not set.
```
TASK [jfrog.installers.artifactory_nginx_ssl : restart nginx] ****************************************************************
fatal: [art2]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
fatal: [art1]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
```

Checking _journalctl -xe_ can see the issue seLinux permission is not correct for nginx to read the certificate file.
```
Nov 12 12:39:11 atfapp01 systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has failed.
--
-- The result is failed.
Nov 12 12:39:11 atfapp01 systemd[1]: Unit nginx.service entered failed state.
Nov 12 12:39:11 atfapp01 systemd[1]: nginx.service failed.
Nov 12 12:39:12 atfapp01 dbus[716]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
Nov 12 12:39:13 atfapp01 setroubleshoot[13181]: failed to retrieve rpm info for /var/opt/jfrog/nginx/ssl/cert.pem
Nov 12 12:39:14 atfapp01 setroubleshoot[13181]: SELinux is preventing /usr/sbin/nginx from read access on the file /var/opt/jf
Nov 12 12:39:14 atfapp01 python[13181]: SELinux is preventing /usr/sbin/nginx from read access on the file /var/opt/jfrog/ngin
```

Looking at the **artifactory_nginx_ssl** role its appears its missing applying the required seLinux restorecon permission.  Is this know bug and fixed in the upcoming release?

If bug is known and have revised version of the new role in another branch, can you share so I can update my local copy to progress with this Artifactory build as its pre-req the X-Ray build which I need to complete with this collection?

**Comment by chukka** [comment]
@wdrury-uk  I think its a known issue FYI- The SELinux configuration is not checked by the role. It needs to be manually changed to permissive before installing the software
Workaround: Change SELinux configuration to permissive and reboot instance

**Comment by wdrury-uk** [comment]
@chukka Thanks for confirming.  Sadly this has not resolved the issue and only way I can progress seems to be to regress to blank VMs so its clean build every time.  If you re-run the Collection Ansible it breaks the conf file permissions.

Do you have a list of known bugs in this release so I know upfront instead of of engineers progressing with this release?
Also where is the scope for the release documented (ReadMe.MD) ?  It doesn't seem to mention seLinux is not included, or what versions this release supports?  This would help alot with our internal backlog planning - thanks up front :)

**Comment by chukka** [comment]
Sure , will add this ASAP and created issue for Selinux  #61

**Comment by chukka** [comment]
@wdrury-uk FYI #63
