### ISSUE TITLE
[ansible] RHEL/Centos 7.8 +Selinux not supported yet

### ISSUE THREAD

**Issue by chukka** [jfrog/JFrog-Cloud-Installers#61]
FYI, we are planning to support RHEL/Centos 7.8 with Selinux in the upcoming releases which is planned for next month

**Comment by jlosito** [comment]
@chukka Is this still true? I wanted to spun up a JFrog instance on CentOS 7 and was curious if the new release resolved this issue.

**Comment by chukka** [comment]
@jlosito Sorry, we don't support Centos 7/8 on 1.x of collections yet, We are planning to push a release of 2.x collections very soon (end of this quarter mostly ) which supports all centos, debian and ubuntu LTS versions
