### ISSUE TITLE
[ansible/xray] MV untar directory to xray home exists

### ISSUE THREAD

**Issue by wdrury-uk** [jfrog/JFrog-Cloud-Installers#64]
**Installer:** Ansible Galaxy

**JFrog Ansible Collection:** jfrog.installers v1.1.2

**What happened**:
Execute basic play to install XRay failed, fixed issue and re-execute play as per normal for Ansible playbook due to its idempotency state.

**What you expected to happen**:
X-Ray to be installed with issue and Success.

**How to reproduce it** (as minimally and precisely as possible):
Create you inventory host file as per example
Create basic playbook to install X-Ray as per example
Execute the playbook, it will error first time due to the know Postgres Init - D error under issue #36 
Fix the err by manually init Postgres as prescribed in issue #36 
Re-execute playbook and it will now fail on the "MV untar directory xray home" task

**Anything else we need to know**:
The error which is displayed when fails because the destination already exists:
```
TASK [jfrog.installers.xray : MV untar directory to xray home] **********************************************************************
task path: /root/.ansible/collections/ansible_collections/jfrog/installers/roles/xray/tasks/install.yml:37
fatal: [xry1]: FAILED! => {"changed": true, "cmd": ["mv", "/opt/jfrog/jfrog-xray-3.3.0-linux", "/opt/jfrog/xray"], "delta": "0:00:00.012358", "end": "2020-11-19 08:00:28.848768", "msg": "non-zero return code", "rc": 1, "start": "2020-11-19 08:00:28.836410", "stderr": "mv: cannot move ‘/opt/jfrog/jfrog-xray-3.3.0-linux’ to ‘/opt/jfrog/xray/jfrog-xray-3.3.0-linux’: File exists", "stderr_lines": ["mv: cannot move ‘/opt/jfrog/jfrog-xray-3.3.0-linux’ to ‘/opt/jfrog/xray/jfrog-xray-3.3.0-linux’: File exists"], "stdout": "", "stdout_lines": []}
```

Looking at the code the issue is because the task is using a Command to execute and thus not able to establish idempotency.  Its better to untar the tarball file to the destination folder the MV is try to make the destination.

**Comment by chukka** [comment]
@wdrury-uk Thanks for reporting , We already have an internal tracking issue  for this (idempotency for all products) and As informed  earlier , we will be able to release this next month :)

Workaround : manually delete `/opt/jfrog/xray` directory

**Comment by wdrury-uk** [comment]
Thanks @chukka I did implement that workaround too.

Is there a published list of the known defects I can check save raising GitHub issues and can also review/use as KB to get workarounds?  The enterprise I work in has JFrog account manager, so can raise them via JFrog support aswell if easier?

**Comment by chukka** [comment]
Sure, I already shared with him list of known issues , please check with him

**Comment by wdrury-uk** [comment]
Is there an update please as new version of the collection advised on my other issues was December 2020.  Whats the new ETA of the next collection version fixing this issue?
