### ISSUE TITLE
[Ansible/all] Documentation should describe ports used by service

### ISSUE THREAD

**Issue by michaeloa** [jfrog/JFrog-Cloud-Installers#94]
**Which installer**:

All

**Which product and version** (eg: ansible & collection version - 1.1.2):

All

**Which operating system and version**(eg: ubuntu & version - 20.4):

All

**What happened**:

Setting up service failed due to port issues.

**What you expected to happen**:

Documentation (README) should describe which ports must be opened in order for the services to run. The default settings for any modern cloud environment is to lock everything down, so a service should never assume that ports, etc., will be open.

**Comment by chukka** [comment]
@michaeloa  Makes sense . can you please help with list of ports (examples) you are looking at documentation so that i can pass on to our documentation team

**Comment by michaeloa** [comment]
In our jfrog platform role, we run:

    - role: jfrog.firewall
      vars:
        firewall_allowed_tcp_ports:
          - "22"
          - "80"
          - "443"
          - "8081"
          - "8082"

jfrog.firewall is basically just geerlingguy's firewall playbook. 22 is for ssh, of course, 80/443 for the web access, but then in addition you have 8081 (for artifactory) and 8082 (for xray). Not sure about how well artifactory deals with 8081 being closed, but the xray install role completely failed when 8082 was not open. The JFrog documentation (and error messages) also mention a ton of other ports, but most of those were internal, and we were able to install without them.

**Comment by chukka** [comment]
@michaeloa  Please refer this page for more Info on ports:

https://www.jfrog.com/confluence/display/JFROG/System+Requirements#SystemRequirements-RequirementsMatrix
