### ISSUE TITLE
Cant download Jfrog Artifactory on AWS ( following your tutorial on Github )

### ISSUE THREAD

**Issue by zyriuse75** [jfrog/JFrog-Cloud-Installers#95]
hi 
When i follow what you have written in [JfrogContainerRestry to install it in AWS ](https://github.com/jfrog/JFrog-Cloud-Installers/tree/aws-jcr-6.15.0/JFrogContainerRegistry/aws/container) i cant AWS ask me for credential , i ve put mine on. but it still doesn't work   ?

**Comment by vasukinjfrog** [comment]
Closing as part of cleanup: Updated Guides available at
For Setup
https://jfrog.com/help/r/jfrog-integrations-documentation/set-up-the-jfrog-container-registry-in-the-aws-container-marketplace-listing

For Upgrade:
https://jfrog.com/help/r/jfrog-integrations-documentation/upgrade-jfrog-container-registry-in-the-aws-container-marketplace-listing
