### ISSUE TITLE
How to find the password for JFrog Container Registry for AWS Container Marketplace

### ISSUE THREAD

**Issue by zyriuse75** [jfrog/JFrog-Cloud-Installers#96]
[jfrog cloud-installer ](https://github.com/jfrog/JFrog-Cloud-Installers/tree/master/Amazon/containers)

what i did to find my password for jfrog 
the command given on your documentation is wrong the file doesn't existe 
 `docker exec -it <container-id> cat /var/opt/jfrog/artifactory/generated-pass.txt`

to find the password : 
`docker exec -it $INSTANCE_ID grep -i password /var/opt/jfrog/artifactory/etc/system.yaml`

**Comment by vasukinjfrog** [comment]
Close as part of cleanup:

Amazon AWS Container Marketplace does not allow default passwords. You must provide a password during container initialization or one will be randomly generated.

To set the first-time initialization password for the 'admin' user, pass the environment variable 
ARTIFACTORY-PASSWORD with the desired password.

https://jfrog.com/help/r/jfrog-integrations-documentation/set-up-the-jfrog-container-registry-in-the-aws-container-marketplace-listing
